export const countries = [
  { name: 'Australia', code: 'AU', dialCode: '+61' },
  { name: 'Brazil', code: 'BR', dialCode: '+55' },
  { name: 'Cameroon', code: 'CM', dialCode: '+237' },
  { name: 'Canada', code: 'CA', dialCode: '+1' },
  { name: 'China', code: 'CN', dialCode: '+86' },
  { name: 'Egypt', code: 'EG', dialCode: '+20' },
  { name: 'Ethiopia', code: 'ET', dialCode: '+251' },
  { name: 'France', code: 'FR', dialCode: '+33' },
  { name: 'Germany', code: 'DE', dialCode: '+49' },
  { name: 'Ghana', code: 'GH', dialCode: '+233' },
  { name: 'India', code: 'IN', dialCode: '+91' },
  { name: 'Italy', code: 'IT', dialCode: '+39' },
  { name: 'Ivory Coast', code: 'CI', dialCode: '+225' },
  { name: 'Kenya', code: 'KE', dialCode: '+254' },
  { name: 'Netherlands', code: 'NL', dialCode: '+31' },
  { name: 'Nigeria', code: 'NG', dialCode: '+234' },
  { name: 'Portugal', code: 'PT', dialCode: '+351' },
  { name: 'Rwanda', code: 'RW', dialCode: '+250' },
  { name: 'Saudi Arabia', code: 'SA', dialCode: '+966' },
  { name: 'Senegal', code: 'SN', dialCode: '+221' },
  { name: 'South Africa', code: 'ZA', dialCode: '+27' },
  { name: 'Spain', code: 'ES', dialCode: '+34' },
  { name: 'Sweden', code: 'SE', dialCode: '+46' },
  { name: 'Tanzania', code: 'TZ', dialCode: '+255' },
  { name: 'Uganda', code: 'UG', dialCode: '+256' },
  { name: 'United Arab Emirates', code: 'AE', dialCode: '+971' },
  { name: 'United Kingdom', code: 'GB', dialCode: '+44' },
  { name: 'United States', code: 'US', dialCode: '+1' },
  { name: 'Zambia', code: 'ZM', dialCode: '+260' },
  { name: 'Zimbabwe', code: 'ZW', dialCode: '+263' },
];
