export const countries = [
  { name: 'Australia', code: 'AU', dialCode: '+61', currency: 'AUD', flag: '🇦🇺' },
  { name: 'Brazil', code: 'BR', dialCode: '+55', currency: 'BRL', flag: '🇧🇷' },
  { name: 'Cameroon', code: 'CM', dialCode: '+237', currency: 'XAF', flag: '🇨🇲' },
  { name: 'Canada', code: 'CA', dialCode: '+1', currency: 'CAD', flag: '🇨🇦' },
  { name: 'China', code: 'CN', dialCode: '+86', currency: 'CNY', flag: '🇨🇳' },
  { name: 'Egypt', code: 'EG', dialCode: '+20', currency: 'EGP', flag: '🇪🇬' },
  { name: 'Ethiopia', code: 'ET', dialCode: '+251', currency: 'ETB', flag: '🇪🇹' },
  { name: 'France', code: 'FR', dialCode: '+33', currency: 'EUR', flag: '🇫🇷' },
  { name: 'Germany', code: 'DE', dialCode: '+49', currency: 'EUR', flag: '🇩🇪' },
  { name: 'Ghana', code: 'GH', dialCode: '+233', currency: 'GHS', flag: '🇬🇭' },
  { name: 'India', code: 'IN', dialCode: '+91', currency: 'INR', flag: '🇮🇳' },
  { name: 'Italy', code: 'IT', dialCode: '+39', currency: 'EUR', flag: '🇮🇹' },
  { name: 'Ivory Coast', code: 'CI', dialCode: '+225', currency: 'XOF', flag: '🇨🇮' },
  { name: 'Kenya', code: 'KE', dialCode: '+254', currency: 'KES', flag: '🇰🇪' },
  { name: 'Netherlands', code: 'NL', dialCode: '+31', currency: 'EUR', flag: '🇳🇱' },
  { name: 'Nigeria', code: 'NG', dialCode: '+234', currency: 'NGN', flag: '🇳🇬' },
  { name: 'Portugal', code: 'PT', dialCode: '+351', currency: 'EUR', flag: '🇵🇹' },
  { name: 'Rwanda', code: 'RW', dialCode: '+250', currency: 'RWF', flag: '🇷🇼' },
  { name: 'Saudi Arabia', code: 'SA', dialCode: '+966', currency: 'SAR', flag: '🇸🇦' },
  { name: 'Senegal', code: 'SN', dialCode: '+221', currency: 'XOF', flag: '🇸🇳' },
  { name: 'South Africa', code: 'ZA', dialCode: '+27', currency: 'ZAR', flag: '🇿🇦' },
  { name: 'Spain', code: 'ES', dialCode: '+34', currency: 'EUR', flag: '🇪🇸' },
  { name: 'Sweden', code: 'SE', dialCode: '+46', currency: 'SEK', flag: '🇸🇪' },
  { name: 'Tanzania', code: 'TZ', dialCode: '+255', currency: 'TZS', flag: '🇹🇿' },
  { name: 'Uganda', code: 'UG', dialCode: '+256', currency: 'UGX', flag: '🇺🇬' },
  { name: 'United Arab Emirates', code: 'AE', dialCode: '+971', currency: 'AED', flag: '🇦🇪' },
  { name: 'United Kingdom', code: 'GB', dialCode: '+44', currency: 'GBP', flag: '🇬🇧' },
  { name: 'United States', code: 'US', dialCode: '+1', currency: 'USD', flag: '🇺🇸' },
  { name: 'Zambia', code: 'ZM', dialCode: '+260', currency: 'ZMW', flag: '🇿🇲' },
  { name: 'Zimbabwe', code: 'ZW', dialCode: '+263', currency: 'ZWL', flag: '🇿🇼' },
];
